### Test Login
POST http://localhost:8000/dj-rest-auth/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "bigL20**"
}

### Test registration
POST http://localhost:8000/dj-rest-auth/registration/
Content-Type: application/json

{
    "username": "testuser3",
    "email": "test3@test.com",
    "password1": "bigL20**",
    "password2": "bigL20**"
}

### Test Fetch post list
GET http://localhost:8000/api/posts/
Content-Type: application/json

